# @package _global_
dataset_name: gigahand
robot_type: xhand
embodiment_type: bimanual
task: p36-tea
temperature: 1.0
data_id: 0
ctrl_dt: 1.5
knot_dt: 0.5
horizon: 3.0
first_ctrl_noise_scale: 1.0
last_ctrl_noise_scale: 2.0
improvement_threshold: -1.0
improvement_check_steps: 2
max_num_iterations: 8
base_pos_rew_scale: 0.1
base_rot_rew_scale: 0.03
joint_noise_scale: 0.03
pos_noise_scale: 0.03
rot_noise_scale: 0.01
final_noise_scale: 0.01
object_rot_threshold: 0.5
max_local_retries: 3
