# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

'''
    Side-by-side gesture comparison for headless servers.

    Left: the MANO human hand mesh performing a gesture (generated by mano_gesture.py).
    Right: the robot hand retargeting the SAME frames through the trained GeoRT model.
    Both are rendered in the browser via viser (no display needed), so you can directly
    see whether the robot reproduces the human gesture.

    Run in the `geort` env:
        python geort/mocap/compare_viser.py -hand wuji -ckpt_tag wuji_mano -data mano_gesture

    Then forward the port and open the URL:
        ssh -L 8080:localhost:8080 <user>@<server>   # http://localhost:8080
'''

import argparse
import time

import numpy as np
import viser
from viser.extras import ViserUrdf

from geort import get_config
from geort.utils.path import get_data_root
from geort.env.hand_viser import resolve_urdf_path

SKIN = (224, 172, 144)
OFFSET = 0.22  # half the lateral gap between the two hands (meters)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-hand', type=str, default='wuji')
    parser.add_argument('-ckpt_tag', type=str, default='wuji_mano')
    parser.add_argument('-data', type=str, default='mano_gesture')
    parser.add_argument('--epoch', type=int, default=0, help='checkpoint epoch (<=0 -> last.pth)')
    parser.add_argument('--host', type=str, default='0.0.0.0')
    parser.add_argument('--port', type=int, default=8080)
    parser.add_argument('--fps', type=float, default=20.0)
    args = parser.parse_args()

    config = get_config(args.hand)
    data_root = get_data_root()
    kp = np.load(data_root / f'{args.data}.npy')                  # [T,21,3]
    mesh = np.load(data_root / f'{args.data}_mano.npz')           # MANO mesh
    verts, faces = mesh['verts'].astype(np.float32), mesh['faces']
    T = len(kp)
    print(f"Loaded {T} frames; MANO mesh {verts.shape}, faces {faces.shape}.")

    # Retargeted joint angles, in config joint_order. Prefer a precomputed
    # data/<name>_qpos.npy so the demo runs with NO torch (e.g. on macOS); otherwise run
    # the model once (needs torch; CPU is fine) and cache the result.
    qpos_path = data_root / f'{args.data}_qpos.npy'
    if qpos_path.exists():
        QPOS = np.load(qpos_path)
        assert len(QPOS) == T, f"qpos length {len(QPOS)} != frames {T}"
        print(f"Using precomputed qpos {QPOS.shape} (torch-free).")
    else:
        print("No precomputed qpos found; loading model (requires torch)...")
        from geort import load_model
        model = load_model(args.ckpt_tag, epoch=args.epoch)
        QPOS = np.stack([model.forward(kp[t]) for t in range(T)])
        np.save(qpos_path, QPOS)
        print(f"Cached qpos -> {qpos_path}")

    server = viser.ViserServer(host=args.host, port=args.port)
    server.scene.set_up_direction('+z')

    # Robot hand on the -Y side, offset via its root node.
    wuji_frame = server.scene.add_frame('/wuji', show_axes=False, position=(0.0, -OFFSET, 0.0))
    urdf = ViserUrdf(server, urdf_or_path=resolve_urdf_path(config['urdf_path']), root_node_name='/wuji')
    wuji_frame.position = (0.0, -OFFSET, 0.0)  # ensure offset sticks after URDF load

    # qpos (config joint_order) -> URDF actuated-joint order, with limits for clipping.
    urdf_joint_names = urdf.get_actuated_joint_names()
    cfg_index = {n: i for i, n in enumerate(config['joint_order'])}
    perm = np.array([cfg_index[n] for n in urdf_joint_names])
    limits = urdf.get_actuated_joint_limits()
    lo = np.array([(limits[n][0] if limits[n][0] is not None else -np.pi) for n in urdf_joint_names])
    hi = np.array([(limits[n][1] if limits[n][1] is not None else np.pi) for n in urdf_joint_names])

    server.scene.add_label('/lbl_mano', 'MANO (human)', position=(0.0, OFFSET, 0.26))
    server.scene.add_label('/lbl_wuji', 'Wuji (retargeted)', position=(0.0, -OFFSET, 0.26))

    play = server.gui.add_checkbox('Play', initial_value=True)
    fps = server.gui.add_slider('Speed (fps)', min=1.0, max=60.0, step=1.0, initial_value=args.fps)
    frame = server.gui.add_slider('Frame', min=0, max=T - 1, step=1, initial_value=0)

    def render_frame(t):
        t = int(t) % T
        server.scene.add_mesh_simple('/mano_hand', vertices=verts[t], faces=faces,
                                     color=SKIN, position=(0.0, OFFSET, 0.0), flat_shading=False)
        qpos = np.asarray(QPOS[t])[perm]
        urdf.update_cfg(np.clip(qpos, lo, hi))

    @frame.on_update
    def _(_):
        if not play.value:
            render_frame(frame.value)

    render_frame(0)
    print(f"\nViser running on port {args.port}. Forward it and open the URL above.\n")

    t = 0
    while True:
        if play.value:
            render_frame(t)
            frame.value = t
            t = (t + 1) % T
        time.sleep(1.0 / max(fps.value, 1.0))


if __name__ == '__main__':
    main()
